### ISSUE TITLE
Typo: Simulacra in Node.sol is undefined?

### ISSUE THREAD

**Issue by harshjv** [nebulis-io/directory#1]
In `Simulacra.sol`

    contract simulacra {
        ...
    }

In `Node.sol`

    import "Simulacra.sol";
    contract Node is Simulacra {
        ...
    }

`Simulacra` or `simulacra` in `Simulacra.sol`?

/cc @Physes

**Comment by Physes** [comment]
Yes, I'll fix this today.

**Comment by Physes** [comment]
Fixed in commit 6a639ed8366e35f810f9fdb92fda669fddc13d61.
